version: "3.8"

services:
  app-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: streamer-watch-app-dev
    container_name: streamer-watch-app-dev
    environment:
      NODE_PATH: /usr/local/lib/node_modules
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    init: true
    working_dir: /app/
    volumes:
      - ./app/:/app/
    ports:
      - "4000:4000"
